on:
  workflow_dispatch:
    inputs:
      ENV:
        description: "Environment to run the tests (dev or prod)"
        required: true
        default: "dev"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -sLo allure.zip https://github.com/allure-framework/allure2/releases/download/2.22.0/allure-2.22.0.zip
          unzip allure.zip -d /opt/allure
          sudo ln -s /opt/allure/allure-2.22.0/bin/allure /usr/local/bin/allure

      # Добавляем команду для проверки файлов
      - name: Check test file existence
        run: |
          ls -la tests/
          ls -la tests/endpoints
          cat tests/endpoints/ava.jpg || echo "File not found or unreadable"

      - name: Run tests with Pytest
        env:
          ENV: ${{ github.event.inputs.ENV }}
        run: |
          mkdir -p ./allure-results
          pytest -n=auto --env=${{ github.event.inputs.ENV }} --alluredir=./allure-results -v

      - name: Check allure-results directory
        if: always()
        run: |
          ls -la ./allure-results

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate ./allure-results -o ./allure-report --clean

      - name: Upload Allure Report as Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-report
          retention-days: 1

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
