on:
  workflow_dispatch:
    inputs:
      ENV:
        description: "Environment to run the tests (dev or prod)"
        required: true
        default: "dev"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -sLo allure.zip https://github.com/allure-framework/allure2/releases/download/2.22.0/allure-2.22.0.zip
          unzip allure.zip -d /opt/allure
          sudo ln -s /opt/allure/allure-2.22.0/bin/allure /usr/local/bin/allure

      - name: Set permissions for ava.jpeg
        run: chmod +r ava.jpeg

      - name: Verify permissions
        run: ls -l ava.jpeg

      - name: Run tests with Pytest
        env:
          ENV: ${{ github.event.inputs.ENV }}
        run: |
          pytest --env=${{ github.event.inputs.ENV }} ./tests/endpoints/test_avatar.py::test_update_avatar -vvv -s