name: Run Pytest and Generate Allure Report

on:
  workflow_dispatch:

env:
  ALLURE_RESULTS_DIR: allure-results
  ALLURE_REPORT_DIR: allure-report

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout кода
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Настройка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # 3. Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Запуск тестов с pytest и сохранение результатов Allure
      - name: Run tests with Pytest
        env:
          ENV: ${{ secrets.ENV }} # Подключение переменной ENV из Secrets
        run: |
          mkdir -p $ALLURE_RESULTS_DIR
          pytest --env=$ENV --alluredir=$ALLURE_RESULTS_DIR

      # 5. Генерация отчета Allure
      - name: Generate Allure Report
        run: |
          allure generate $ALLURE_RESULTS_DIR -o $ALLURE_REPORT_DIR --clean

      # 6. Сохранение Allure отчета как артефакта
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report