on:
  workflow_dispatch:
    inputs:
      ENV:
        description: "Environment to run the tests (dev or prod)"
        required: true
        default: "dev"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -sLo allure.zip https://github.com/allure-framework/allure2/releases/download/2.22.0/allure-2.22.0.zip
          unzip allure.zip -d /opt/allure
          sudo ln -s /opt/allure/allure-2.22.0/bin/allure /usr/local/bin/allure

      # Добавляем команду для проверки файлов
      - name: Check test file existence
        run: |
          ls -la tests/
          ls -la tests/endpoints
          cat tests/endpoints/ava.jpg || echo "File not found or unreadable"
          cat tests/endpoints/ava.jpg || echo "File not found or unreadable"
        if: always()

      - name: Run tests with Pytest
        env:
          ENV: ${{ github.event.inputs.ENV }}
        run: |
          mkdir -p ./allure-results
          pytest -n=auto --env=${{ github.event.inputs.ENV }} --alluredir=./allure-results -v
        if: always()

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: ./allure-results
          allure_history: ./allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./allure-history